### PR TITLE
Add purego driver

### PR DESCRIPTION
**Pull request by Arsen6331**
- [X] Do only one thing
- [X] Non breaking API changes
- [X] Tested

### What did this pull request do?

This PR adds a purego driver that can be built via tags. The test for purego doesn't use a custom function on the custom driver as it is currently impossible to do that. It instead registers the function on the default driver. The cgo test is unchanged. Other than that, everything should work the same, just pass `-tags purego` when building or testing to switch to the purego driver. Building without the flag will build using the cgo driver.

If anything should be changed, I would be happy to do so.

#77

### User Case Description

My use case for this change is easy cross-compilation and portability of binaries using GORM.

### CODE REVIEW

**Comment by glebarez** [comment]
@Arsen6331, to pass as GORM compatible driver, this should also succeed in all tests of GORM itself (see https://github.com/go-gorm/gorm/tree/master/tests).
You can trigger those tests via Github actions, just make a PR to https://github.com/go-gorm/playground, making changes in go.mod and go.sum to point the tests to your sqlite driver.

Hope this helps to clear things out.

**Comment by Arsen6331** [comment]
How would I pass a tag to github actions? You need to pass the `-tags purego` flag to `go build`, `go test`, etc. to use the new driver.

**Comment by Arsen6331** [comment]
I ran the tests on my desktop. It passed, here are the results:

```
$ GORM_DIALECT=sqlite CGO_ENABLED=0 go test -tags purego
2022/05/11 16:29:23 testing sqlite3...

2022/05/11 16:29:23 /home/arsen/Workspace/playground/main_test.go:14
[0.214ms] [rows:1] INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`age`,`birthday`,`company_id`,`manager_id`,`active`) VALUES ("2022-05-11 16:29:23.801","2022-05-11 16:29:23.801",NULL,"jinzhu",0,NULL,NULL,NULL,false) RETURNING `id`

2022/05/11 16:29:23 /home/arsen/Workspace/playground/main_test.go:17
[0.073ms] [rows:1] SELECT * FROM `users` WHERE `users`.`id` = 1 AND `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT 1
PASS
ok  	gorm.io/playground	0.015s
```

**Comment by Arsen6331** [comment]
I've figured out how to do the tests in the playground repo: go-gorm/playground#476

**Comment by Arsen6331** [comment]
I just tried disabling CGo, and the test failed because -race needs CGo according to the error message. I removed -race and the test succeeded, so it is in fact using the driver I added.

**Comment by jinzhu** [comment]
sounds a reasonable solution for me, but seems like the gorm tests failed even w/o the `race` tag

**Comment by Arsen6331** [comment]
> sounds a reasonable solution for me, but seems like the gorm tests failed even w/o the `race` tag

The latest test is successful, with cgo disabled.

**Comment by jinzhu** [comment]
`GORM_DIALECT=sqlite CGO_ENABLED=0 go test -tags purego` still fail for me for those tests. https://github.com/go-gorm/gorm/tree/master/tests

**Comment by Arsen6331** [comment]
> `GORM_DIALECT=sqlite CGO_ENABLED=0 go test -tags purego` still fail for me for those tests. [https://github.com/go-gorm/gorm/tree/master/tests](https://github.com/go-gorm/gorm/tree/master/tests?rgh-link-date=2022-05-17T02%3A28%3A22Z)

I just tried, they do seem to fail. Interestingly, https://github.com/glebarez/sqlite imports https://github.com/glebarez/go-sqlite, which uses the same driver as I do here ([modernc.org/sqlite](https://modernc.org/sqlite)) but doesn't fail the tests. I'm not sure what the difference is between them.

**Comment by glebarez** [comment]
the https://github.com/glebarez/go-sqlite is a slightly different frontend (database/sql implementation) for modernc.org/sqlite.
Thus it behaves more like https://github.com/mattn/go-sqlite3, but uses pure-go sqlite under the hood. 
That's the reason it succeeds in GORM tests. It's not just a simple dependency switch.

**Comment by Arsen6331** [comment]
Ok then, I'll modify the PR to use glebarez/go-sqlite if you don't mind.

**Comment by glebarez** [comment]
> Ok then, I'll modify the PR to use glebarez/go-sqlite if you don't mind.

Well, it's still not going to work as a simple tag switch for existing users of this driver, because modernc.org/sqlite (and https://github.com/glebarez/go-sqlite) still uses different syntax for PRAGMA specification in connection strings (e.g. enabling foreign-key constraint)

**Comment by Arsen6331** [comment]
According to https://pkg.go.dev/modernc.org/sqlite#Open and https://github.com/glebarez/go-sqlite#connection-string-examples, both use `?_pragma=foreign_keys(1)` for that.

**Comment by Arsen6331** [comment]
I just tried using https://github.com/glebarez/go-sqlite, and all the gorm tests succeeded.

**Comment by Arsen6331** [comment]
It looks like it wouldn't be too difficult to convert between the two syntaxes, if that's a suitable solution. A better solution might just be to document this in the README and warn users about the difference.

**Pull request closed without merging**
